<?php

// J'ouvre cette session base.phtml (qui est ma nav_bar et mon footer) pour l'afficher sur toute les pages de mon portfolio.
// Fonction qui me permet de savoir si elle n'a pas déjà été ouverte précédement :
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

?>

<!DOCTYPE html>

<html lang="en">
	<head>

		<!-- Meta Tags -->
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />

		<!-- Bootstrap CSS -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

		<!-- Animate on scroll Library CSS -->
    	<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

		<!-- Librariesfont-awesome CDN -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

		<!-- Feuille de style CSS portfolio_style.css -->
		<link rel="stylesheet" type="text/css" href="portfolio_style.css">

	<title>Julien Perrot -  <?= $title ?? '' ?></title>
	<link rel="icon" type="image/png" sizes="32x32" href="assets/favicon-32x32.png">

	</head>

    <body>
		<main class="main_background">
			<header class="header">
				<nav class="navbar navbar-expand-lg navbar-dark">
					<div class="container-fluid">
						<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
							<span class="navbar-toggler-icon"></span>
						</button>
						<div class="text_nav_left">
							<ul class="navbar-nav justify-content-center">
								<li class="nav-item">
									<a id="css_link_nav" class="nav-link active">Bonne visite</a>
								</li>
							</ul>
						</div>
						<div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
							<ul class="navbar-nav">
								<li class="nav-item">
									<a id="css_link_nav" class="nav-link active" aria-current="page" href="#">Accueil</a>
								</li>
								<li class="nav-item">
									<a id="css_link_nav" class="nav-link active" href="#presentation">Présentation</a>
								</li>
								<li class="nav-item">
									<a id="css_link_nav" class="nav-link active" href="#competences">Compétences</a>
								</li>
								<li class="nav-item">
									<a id="css_link_nav" class="nav-link active" href="#projets">Projets</a>
								</li>
								<li class="nav-item">
									<a id="css_link_nav" class="nav-link active" target="_blank" href="assets/CV Julien.pdf">CV</a>
								</li>
								<li class="nav-item">
									<a id="css_link_nav" class="nav-link active" href="#contact">Contact</a>
								</li>
							</ul>
						</div>
					</div>
				</nav>
			</header>

			<!-- Je récupére toute la template de mon dossier index.phtml pour ma page d'accueil : -->
			<section>
				<?php require $template . '.phtml' ?>
			</section>

			<footer>
				<div class="row responsive_footer">
					<div class="col-3 text-center copyright">
						<div class="text_footer">
							<p><img src="assets/copyright.png" width="40px" height="40px" alt="Logo copyright">opyright 2021</p>
							<p class="text-center">Produit créer par mes doigts, destiner à montrer mes compétences dans le développement Web en vue de ma reconversion professionnelle.</p> 
						</div>
					</div>

					<div class="col-6 text_typing_footer">
						<div class="typing_footer">
							<p>Un grand <span class="responsive_768px">Merci pour votre visite.</span><span class="type_footer"><span>MERCI pour votre visite.</span></span></p>
						</div>
					</div>

					<div class="col-3 logo_footer">
						<div>
							<div>
								<p>Soyez curieux,</br>clique et visite.</p>
								<div class="logo">
								<a href="https://www.linkedin.com/in/julien-perrot-aa9355219/" target="_blank">
									<img src="assets/linkedin.png" width="45px" height="45px" alt="Logo linkedin">
								</a>
								<a href="https://github.com/Julien-Perrot" target="_blank">
									<img src="assets/github-logo.png" width="45px" height="45px" alt="Logo github">
								</a>
								</div>
							</div>
						</div>
					</div>
				</div>

				<span id="myBtn" title="Go to top">
					<a href="#">
						<img src="assets/arrow-up.png" class="logo_up_scroll" width="40px" height="40px" alt="Logo fléche">
					</a>
				</span>
			</footer>
		</main>

        <!-- Animate on scroll Library JavaScript -->
    	<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

        <!-- JQuery -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

        <!-- Bootstrap JavaScript -->
		<script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

		<script>AOS.init();</script>
		<script src="portfolio_script.js"></script>
	
    </body>
</html>