    <section class="start">
        <div class="background">	
            <div class="overlay">
                <div class="title_position">
                    <a class="name" href="#">Julien PERROT</a>
                </div>
                <div class="row justify-content-center">
                    <div class="col-6 margin_title">
                        <h1 class="title anim_title">Bonjour,</h1>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-4"></div>
                        <div class="col-6 margin_typing">
                            <div class="typing">
                                <h2 class="typewrite"></h2>
                            </div>
                        <div class="col-2"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>

	<div class="col-12 lien_span">
		<hr><span id="presentation"></span>
	</div>

    <section>
		<div class="title_main">
			<h3 id="presentation">PRESENTATION</h3>
		</div>	
		<div class="row presentation">
			<div class="col-4 table_responsive">
				<img src="assets/julien.png" alt="Photo de profil">
			</div>
			<div class="col-8 text_presentation">
				<p>
					Bonjour, je m’appelle Julien et je suis développeur web junior.
				</p>
				<p>
					Anciennement technicien diagnostique dans le domaine des camion et bus, j’ai décidé de rendre mes outils et mon bleu de travail pour me consacrer pleinement à mon nouvel objectif : apprendre à coder.
				</p>
				<p>
					C’est en suivant quelques intégrateur sur Twitch & YouTube que mon intérêt pour le code est né. Mon intérêt grandissant à grand pas, je décide de suivre des cours en ligne via Openclassroom, puis je décide de m’inscrire au boot camp Web Force 3. Mon admission en poche, je découvre au quotidien l’envers du décor du web et me découvre une nouvelle passion pour un métier qui me fascine tant.
				</p>
				<p>
					Je suis aujourd’hui à la recherche d’un stage pour finaliser ma formation et obtenir ma certification.
					</br>
					Vous voulez me contacter, <a id="mail" href="mailto:p.julien.perrot@hotmail.com?">cliquez ici.</a>
				</p>
			</div>
		</div>
	</section>

    <div class="col-12 lien_span">
		<hr><span id="competences"></span>
	</div>

	<section>
		<div class="title_main">
			<h3>MES COMPETENCES</h3>
		</div>
		<div class="row competences">
			<div class="col-6 none_img_code text-center" data-aos="fade-right" data-aos-duration="1000">
				<img class="shadow bg-body rounded" src="assets/img_competence.jpg" alt="Image de code informatique" height="380px" >
			</div>

			<div class="col-6 progress_responsive" data-aos="fade-left" data-aos-anchor="#example-anchor" data-aos-offset="1500" data-aos-duration="1500">	
				<div class="logo_progress">
					<img src="assets/html5.png" alt="logo html 5" width="40px" height="40px">
					<div class="progress">
						<div class="progress-bar html" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">75%</div>
					</div>
				</div>
				<div class="logo_progress">
					<img src="assets/css-3.png" alt="logo css 3" width="40px" height="40px">
					<div class="progress">
						<div class="progress-bar bg-info" role="progressbar" style="width: 65%" aria-valuenow="65" aria-valuemin="0" aria-valuemax="100">65%</div>
					</div>
				</div>
				<div class="logo_progress">
					<img src="assets/bootstrap.png" alt="logo bootstrap" width="40px" height="40px">
					<div class="progress">
						<div class="progress-bar bootstrap" role="progressbar" style="width: 70%" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100">70%</div>
					</div>
				</div>
				<div class="logo_progress">
					<img src="assets/sass.png" alt="logo sass" width="40px" height="40px">
					<div class="progress">
						<div class="progress-bar sass" role="progressbar" style="width: 30%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100">30%</div>
					</div>
				</div>
				<div class="logo_progress">
					<img src="assets/javascript.png" alt="logo java-script" width="40px" height="40px">	
					<div class="progress">
						<div class="progress-bar bg-warning" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100">40%</div>
					</div>
				</div>
				<div class="logo_progress">
					<img src="assets/jquery.png" alt="logo JQuery" width="40px" height="40px">
					<div class="progress">
						<div class="progress-bar bg-primary" role="progressbar" style="width: 35%" aria-valuenow="35" aria-valuemin="0" aria-valuemax="100">35%</div>
					</div>
				</div>
				<div class="logo_progress">
					<img src="assets/angular.png" alt="logo angular" width="40px" height="40px">
					<div class="progress">
						<div class="progress-bar bg-danger" role="progressbar" style="width: 30%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100">30%</div>
					</div>
				</div>
				<div class="logo_progress">
					<img src="assets/wordpress.png" alt="Logo de wordpress" width="40px" height="40px">
					<div class="progress">
						<div class="progress-bar wordpress" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">50%</div>
					</div>
				</div>
				<div class="logo_progress">
					<img src="assets/mysql.png" alt="logo MY SQL" width="40px" height="40px">
					<div class="progress">
						<div class="progress-bar mysql  " role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100">40%</div>
					</div>
				</div>
				<div class="logo_progress">
					<img src="assets/php.png" alt="logo PHP" width="40px" height="40px">
					<div class="progress">
						<div class="progress-bar php" role="progressbar" style="width: 30%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100">30%</div>
					</div>
				</div>	
			</div>
		</div>
	</section>

	<div class="col-12 lien_span">
		<hr><span id="projets"></span>
	</div>

    <section class="container_projet">
		<div class="title_main">
			<h3 id="projets">MES PROJETS</h3>
		</div>

		<div class="button_projet mb-4">
			<button type="button" class="btn btn-outline-danger btn-sm me-md-2" data-id="1">Tous</button>
			<button type="button" class="btn btn-outline-danger btn-sm me-md-2" data-id="2">Html/CSS</button>
			<button type="button" class="btn btn-outline-danger btn-sm me-md-2" data-id="3">Bootstrap</button>
			<button type="button" class="btn btn-outline-danger btn-sm me-md-2" data-id="4">JavaScript</button>
			<button type="button" class="btn btn-outline-danger btn-sm me-md-2" data-id="5">PHP</button>
			<button type="button" class="btn btn-outline-danger btn-sm me-md-2" data-id="6">Symfony</button>
			<button type="button" class="btn btn-outline-danger btn-sm me-md-2" data-id="7">Projet final</button>
		</div>

		<div class="text-center m-3">
			<p class="fw-lighter fst-italic">Pour information, certains liens dans les cartes de mes projets sont des screenshots. Les pages ne sont pas encore en lignes vu que j'ai des accès limiter de deux bases de données avec mon hébergeur Webhost.</p>
		</div>

		<div class="row line_projet">
			<div class="box-1 col-3 column_projet image_back_1 box box-2 shadow p-3 mb-5 bg-body rounded">	
				<div class="overlay_card_projet">
					<div id="text"><a href="projets/profil_card_index.html" target="_blank">Présentation breve par une carte de visite.</br><img class="mt-3" src="assets/cursor.png" width="40px" height="40px"></a></div>					
				</div>		
			</div>

			<div class="box-1 col-3 column_projet image_back_2 box box-2 shadow p-3 mb-5 bg-body rounded">
				<div class="overlay_card_projet">
					<div id="text"><a href="projets/apprentissage.html" target="_blank">Bannière d'apprentissage.</br><img class="mt-3" src="assets/cursor.png" width="40px" height="40px"></a></div>
				</div>
			</div>

			<div class="box-1 col-3 column_projet image_back_3 box box-2 shadow p-3 mb-5 bg-body rounded">
				<div class="overlay_card_projet">
					<div id="text"><a href="projets/evaluation_html_index.html" target="_blank">Site e-commerce de vente de gant de boxe.</br><img class="mt-3" src="assets/cursor.png" width="40px" height="40px"></a></div>
				</div>
			</div>

			<div class="box-1 col-3 column_projet image_back_4 box box-3 shadow p-3 mb-5 bg-body rounded">
				<div class="overlay_card_projet">
					<div id="text"><a href="projets/travaux_pratiques_0_index.html" target="_blank">Blog photo en Bootstrap.</br><img class="mt-3" src="assets/cursor.png" width="40px" height="40px"></a></div>
				</div>
			</div>
					
			<div class="box-1 col-3 column_projet image_back_5 box box-3 shadow p-3 mb-5 bg-body rounded">	
				<div class="overlay_card_projet">
					<div id="text"><a href="projets/travaux_pratiques_1_index.html" target="_blank">Diverses offres téléphoniques en Bootstrap.</br><img class="mt-3" src="assets/cursor.png" width="40px" height="40px"></a></div>
				</div>		
			</div>
		</div>

		<div class="row line_projet">
			<div class="box-1 col-3 column_projet image_back_6 box box-4 shadow p-3 mb-5 bg-body rounded">	
				<div class="overlay_card_projet">
					<div id="text"><a href="projets/calcul_JS_index.html" target="_blank">Calculer sa moyenne sans l'aide d'une calculatrice.</br><img class="mt-3" src="assets/cursor.png" width="40px" height="40px"></a></div>
				</div>		
			</div>

			<div class="box-1 col-3 column_projet image_back_7 box box-4 shadow p-3 mb-5 bg-body rounded">
				<div class="overlay_card_projet">
					<div id="text"><a href="projets/musique_index.html" target="_blank">Recherche d'artiste et musique par une notation entre 0 & 10.</br><img class="mt-3" src="assets/cursor.png" width="40px" height="40px"></a></div>
				</div>
			</div>

			<div class="box-1 col-3 column_projet image_back_8 box box-4 shadow p-3 mb-5 bg-body rounded">
				<div class="overlay_card_projet">
					<div id="text"><a href="projets/evalJS_index.html" target="_blank">Site de location de voiture avec animation JavaScript (slide, toggle).</br><img class="mt-3" src="assets/cursor.png" width="40px" height="40px"></a></div>
				</div>
			</div>

			<div class="box-1 col-3 column_projet image_back_9 box box-5 shadow p-3 mb-5 bg-body rounded">
				<div class="overlay_card_projet">
					<div id="text"><a href="assets/Capture_d’écran_php_1.png" target="_blank">Gestion des commandes de ventes de maquettes de voitures.</br><img class="mt-3" src="assets/cursor.png" width="40px" height="40px"></a></div>
				</div>
			</div>

			<div class="box-1 col-3 column_projet image_back_10 box box-5 shadow p-3 mb-5 bg-body rounded">	
				<div class="overlay_card_projet">
					<div id="text"><a href="assets/Capture_d’écran_php_2.png" target="_blank">Gestion d'employées dans une entreprise par les ressources humaines.</br><img class="mt-3" src="assets/cursor.png" width="40px" height="40px"></a></div>
				</div>		
			</div>
		</div>

		<div class="row line_projet">
			<div class="box-1 col-3 column_projet image_back_11 box box-6 shadow p-3 mb-5 bg-body rounded">	
				<div class="overlay_card_projet">
					<div id="text"><a href="assets/Capture_d’écran_symfony_1.png" target="_blank">Application pour les donuts du monde entier.</br><img class="mt-3" src="assets/cursor.png" width="40px" height="40px"></a></div>
				</div>		
			</div>

			<div class="box-1 col-3 column_projet image_back_12 box box-6 shadow p-3 mb-5 bg-body rounded">
				<div class="overlay_card_projet">
					<div id="text"><a href="assets/Capture_d’écran_symfony_2.png" target="_blank">Application de lieux du monde à visiter pour les touristes.</br><img class="mt-3" src="assets/cursor.png" width="40px" height="40px"></a></div>
				</div>
			</div>

			<div class="box-1 col-3 column_projet image_back_13 box box-7 shadow p-3 mb-5 bg-body rounded">	
				<div class="overlay_card_projet">
					<div id="text"><a href="" target="_blank">Zikrit, projet final réaliser en groupe de trois personnes. Site de critique et d'achat musical.</br><img class="mt-3" src="assets/cursor.png" width="40px" height="40px"></a></div>
				</div>		
			</div>
		</div>
	</section>

	<div class="col-12 lien_span">
		<hr><span id="contact"></span>
	</div>

	<section class="container_contact">

		<div class="title_main">
			<h3 id="projets">FORMULAIRE DE CONTACT</h3>
			<p class="contact_text">N'hésitez pas à me faire part de vos remarques (positives ou négatives) ainsi que votre ressenti concernant le travail que j'ai effectué pour créer mon tout premier portfolio. </p>
		</div>

		<form method="post" action="add_visiteur.php">

            <?php if (isset($_SESSION['errors'])): ?>
                <div class="row">
                    <div class="col-3"></div>
                        <div class="col-6">
                            <aside class="alert alert-danger">
                                <ul>
                                    <?php foreach ($_SESSION['errors'] as $error): ?>
                                        <li><?= $error ?></li>
                                    <?php endforeach ?>
                                </ul>
                            </aside>
                        </div>
                    <div class="col-3"></div>
                </div>
                
                <?php unset($_SESSION['errors']) ?>
            <?php endif ?>

			<div class="row g-3">
				<div class="col-3"></div>
				<div class="col-md-3">
					<label for="prenom" class="form-label">Prénom :</label>
					<input type="text" class="form-control" id="prenom" name="prenom" require minlength="3" placeholder="Julien">
				</div>
				<div class="col-md-3">
					<label for="nom" class="form-label">Nom :</label>
					<input type="text" class="form-control" id="nom" name="nom" placeholder="Facultatif">
				</div>
				<div class="col-3"></div>
		
				<div class="col-3"></div>
					<div class="col-md-6">
						<label for="email" class="form-label">Email :</label>
						<input type="email" class="form-control" id="e_mail" name="e_mail" placeholder="exemple@gmail.com">
					</div>
			  	<div class="col-3"></div>

				<div class="col-3"></div>
					<div class="col-md-6">
                        <label for="message" class="form-label">Message :</label>
						<textarea type="text" id="message" name="message" class="form-control" style="height: 100px" placeholder="Merci pour votre message."></textarea>
					</div>
				<div class="col-3"></div>
				
				<div class="col-12 d-flex justify-content-center">
					<button type="submit" class="btn btn-outline-danger btn-sm">Envoyer</button>
				</div>
		  	</div>
		</form>
	</section>
		
	<div class="col-12 lien_span">
		<hr>
	</div>